IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Product')
BEGIN
	CREATE TABLE Product (
		Id INT IDENTITY,
		[Name] VARCHAR(50) NOT NULL,
		[Description] VARCHAR(200) NOT NULL,
		DateAdded DATETIME NOT NULL,
		Quantity INT NOT NULL DEFAULT 0
	)
END
